name = "serverless-dns"
main = "./dist/worker.js"
workers_dev = true
# use node_compat or custom build
# node_compat = true
compatibility_date = "2022-08-04"
send_metrics = false

[build]
command = "npm run build"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[vars]
RUNTIME = "worker"
LOG_LEVEL = "debug"
WORKER_ENV = "development"
CLOUD_PLATFORM = "cloudflare"
CF_BLOCKLIST_URL = "https://cfstore.rethinkdns.com/blocklists/"


##################
#------PROD------#
##################
# wrangler doesn't yet support Workers Services and the new "Environments"
# github.com/cloudflare/cloudflare-docs/pull/3175/files
# github.com/cloudflare/wrangler2/issues/27
# developers.cloudflare.com/workers/platform/environments
[env.prod]
name = "basic-unbound"
routes = [
  "sky.rethinkdns.com/*",
  "sky.bravedns.com/*",
  "basic.rethinkdns.com/*",
  "basic.bravedns.com/*",
  "free.bravedns.com/*",
]
# vars are not inherited
# workers/platform/environment-variables#environment-variables-via-wrangler
[env.prod.vars]
RUNTIME = "worker"
LOG_LEVEL = "info"
WORKER_ENV = "production"
CLOUD_PLATFORM = "cloudflare"
CF_BLOCKLIST_URL = "https://cfstore.rethinkdns.com/blocklists/"

##################
#-----SECRETS----#
##################
# only for documentation purposes
# developers.cloudflare.com/workers/platform/environment-variables/#adding-secrets-via-wrangler
# [secrets]
# GW_IP4 = ""
# GW_IP6 = ""
